import csv
from datetime import datetime


### PATH TO THE FILE GENERATED BY THE PREVIOUS PROGRAM ###
csv_file_path = 'Questions/Question 3/Sorting File.csv'

### PATH TO THE OUTPUT FILE ###
output_file_path = 'Questions/Question 3/Sessions R107.csv'
output_file_path2 = 'Questions/Question 4/Sessions R107.csv'

### GROUP TO FILTER ###
search_group = "B2"


### READ THE CSV FILE (path defined earlier) ###
def read_csv_file(file_path):

    with open(file_path, 'r', encoding='utf-8') as file:

        reader = csv.reader(file, delimiter=';')
        next(reader)

        return list(reader)


### KEEP ONLY THE SESSIONS OF R1.07 FOR THE SELECTED GROUP ###
def filter_r107_sessions(csv_table, search_group):

    filtered_sessions = []

    for row in csv_table:

        uid, date, time, duration, modality, title, room, professors, groups = row

        # Remove irrelevant items by filtering groups
        # Decompose into a list by splitting on '|' and remove unnecessary parts
        corrected_groups = "|".join([part.strip() for part in groups.split('|') if search_group in part])

        if "R1.07" in title and search_group in corrected_groups:
            filtered_sessions.append([date, duration, modality])

    return filtered_sessions


### WRITE THE TABLE ###
def write_result_table(output_file_path, filtered_sessions):

    with open(output_file_path, mode='w', newline='', encoding='utf-8') as csv_file:

        # Write the columns
        writer = csv.writer(csv_file, delimiter=';')
        writer.writerow(["Date", "Duration", "Session Type"])
        writer.writerows(filtered_sessions)


csv_table = read_csv_file(csv_file_path)


### FILTER THE SESSIONS OF R1.07 FOR THE SELECTED GROUP ###
filtered_sessions = filter_r107_sessions(csv_table, search_group)


### WRITE THE RESULTS INTO A CSV FILE ###
write_result_table(output_file_path, filtered_sessions)
write_result_table(output_file_path2, filtered_sessions)


# Display the results
print(f"Here are the filtered sessions for the resource R1.07 and the group {search_group}:")

for session in filtered_sessions:
    print(session)
