import pandas as pd
import matplotlib.pyplot as plt
import markdown
from markdown import markdown
import os


### PATH TO THE FILE GENERATED BY THE PREVIOUS PROGRAM ###
csv_file_path = 'Questions/Question 4/Sessions R107.csv'

### PATH TO THE OUTPUT FILE ###
output_file_path = 'Questions\\Question 5\\PieChartTP2.png'

### PATH TO THE FINAL HTML FILE ###
html_file_path = 'Questions\\Question 5\\WorkSessions.html'




### READ THE FILE FROM THE PREVIOUS PROGRAM ###
def read_csv_file(csv_file_path):

    return pd.read_csv(csv_file_path, sep=";")




### DATE CONVERSION ###
def convert_date(df):

    df['Date'] = pd.to_datetime(df['Date'], format='%d-%m-%Y')
    return df



### MONTH + YEAR ###
def add_month_year(df):

    df['Month'] = df['Date'].dt.to_period('M')
    return df.groupby('Month').size()


### PIE CHART ###
def create_pie_chart(course_count_per_month, output_file_path):

    plt.figure(figsize=(8, 8))

    ax = course_count_per_month.plot(kind='pie', autopct='%1.1f%%', startangle=90)

    plt.title('Percentage of Courses by Month', fontsize=16, weight='bold')


    ### SAVE THE CHART ###
    plt.tight_layout()
    plt.savefig(output_file_path)





def generate_html_table(df):

    ### HERE, WE FIRST GENERATE THE TABLE IN MARKDOWN THEN CONVERT IT TO HTML ###
    markdown_table = df.to_markdown(index=False, tablefmt="pipe")
    html_table = markdown(markdown_table, extensions=['tables'])
    
    return html_table




def create_html_file(df, course_count_per_month, output_file_path, html_file_path):

    html_table = generate_html_table(df)

    html_content = f"""

    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        
        <style>
            body {{
                font-family: Arial, sans-serif;
                color: #333;
                margin: 40px;
            }}

            table {{
                width: 100%;
                border-collapse: collapse;
                margin-bottom: 30px;
            }}

            th, td {{
                padding: 8px 12px;
                text-align: center;
                border: 1px solid #ddd;
            }}

            th {{
                background-color: #f4f4f4;
                color: #333;
            }}

            img {{
                display: block;
                margin: 0 auto;
            }}
        </style>
    </head>
    <body>
        <h2>Session Table for R1.07</h2>
        {html_table}
    </body>
    </html>
    """


    with open(html_file_path, 'w', encoding='utf-8') as html_file:
        html_file.write(html_content)






### EXECUTE FUNCTIONS HERE ###
def main():


    df = read_csv_file(csv_file_path)
    df = convert_date(df)

    # GENERATE THE PIE CHART
    course_count_per_month = add_month_year(df)
    create_pie_chart(course_count_per_month, output_file_path)

    ### CREATE AN HTML FILE ###
    create_html_file(df, course_count_per_month, output_file_path, html_file_path)







### PROGRAM START ###
if __name__ == "__main__":
    main()
