import pandas as pd
import matplotlib.pyplot as plt


### PATH TO THE FILE GENERATED BY THE PREVIOUS PROGRAM ###
csv_file_path = 'Questions/Question 4/Sessions R107.csv'

### PATH TO THE OUTPUT FILE ###
output_file_path = 'Questions/Question 4/GraphTP.png'


### READ THE FILE FROM THE PREVIOUS PROGRAM ###
def read_csv_file(csv_file_path):

    return pd.read_csv(csv_file_path, sep=";")


### DATE CONVERSION ###
def convert_date(df):
    
    df['Date'] = pd.to_datetime(df['Date'], format='%d-%m-%Y')
    return df


### MONTH + YEAR ###
def add_month_year(df):

    df['Month'] = df['Date'].dt.to_period('M')
    return df.groupby('Month').size()


### GRAPH ###
def create_graph(course_count_per_month, output_file_path):

    plt.figure(figsize=(10, 6))

    ax = course_count_per_month.plot(kind='bar', color='royalblue', width=0.8, edgecolor='darkblue')


    ### ADD TITLES ###
    plt.xlabel('Month', fontsize=14, weight='bold', color='darkblue')
    plt.ylabel('Number of courses', fontsize=14, weight='bold', color='darkblue')


    ### SAVE THE GRAPH ###
    plt.tight_layout()
    plt.savefig(output_file_path) # You can add DPI if desired, but it’s not mandatory for a graph as we don’t seek optimal quality.


### EXECUTE FUNCTIONS HERE ###
def main():

    df = read_csv_file(csv_file_path)
    df = convert_date(df)

    course_count_per_month = add_month_year(df)
    create_graph(course_count_per_month, output_file_path)


if __name__ == "__main__":
    main()
